version: '3.4'

services:
  book.api:
    container_name: book.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80
  
  price.api:
    container_name: price.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8002:80
    
  api-gateway:
    container_name: api-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - book.api
    ports:
      - 7000:80
   
      
